meta_product_name: "Talkroom"
meta_title: "Talkroom - Free Mental Health Support"
meta_description: "Talkroom is a platform where counselors connect with patients needing mental health support for free. Get the help you need from experienced professionals."
meta_image: "Talkroom.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
